name: webbriks-server-db

services:
  postgres:
    image: postgres:16-alpine
    container_name: webbriks-postgres
    environment:
      POSTGRES_DB: webbriks-technical-assessment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - webbriks_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d webbriks-technical-assessment"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  webbriks_postgres_data:
    name: webbriks_postgres_data
